export enum ActionTypes  {
    GET_SUMMARY = "COVID19/GET_SUMMARY",
    SEARCH_COUNTRIES = 'COVID19/SEARCH_COUNTRIES',
    SORT_TYPE = 'COVID19/SORT_TYPE',
    SELECTED_COUNTRY = 'COVID19/SELECTED_COUNTRY',
}
